# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Environment
      run: sudo apt-get install golang gcc libgl1-mesa-dev xorg-dev docker.io
    
    - name: Set up Fyne base
      run: go get fyne.io/fyne/v2@latest
      
    - name: Set up Fyne cmd tools
      run: go install fyne.io/fyne/v2/cmd/fyne@latest
      
    - name: Set up Fyne Cross
      run: go install github.com/fyne-io/fyne-cross@latest
    
    - name: Build
      run: fyne-cross windows
      
      
