# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Set up Environment
      run: sudo apt-get install gcc libgl1-mesa-dev xorg-dev
      
    - name: Set up Fyne cmd tools
      run: go install fyne.io/fyne/v2/cmd/fyne@latest
      
    - name: Set up Fyne Cross
      run: go install github.com/fyne-io/fyne-cross@latest
      
    - name: add Paths
      run: export GOPATH=$HOME/go && export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
      
    - name: Install Podman
      uses: gacts/install-podman@v1.1.0
    
    - name: Build
      run: pwd -L && fyne-cross windows -app-id work.time.counter
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: all exe
        path: /**/*.exe
      
      
